#dicionary of terms to be subsituted
dic = {'Senator': 'Elf-Lord',
		'Law ': 'Law of the Land ',
		'law ': 'law of the land ',
		'shirt': 'robe',
		'Shirt': 'Robe',
		'Attorney': 'Paladin',
		'attorney': 'paladin',
		'officer': 'knight-errant',
		'Officer': 'Knight-errant',
		'Electriciry': 'Magic',
		'electricity': 'magic',
		'Technology': 'Mage-craft',
		'technology': 'mage-craft',
		'Mayor': 'Minor noble',
		'mayor': 'minor noble',
		'Gun': 'Boomstick',
		'gun': 'boomstick',
		'Knife': 'Stabby thing',
		'knife': 'stabby thing',
		'judge': 'big wig man',
		'investigation': 'whodunnit',
		'witnesses': 'these dudes I know',
		'Russia': 'Land of Ice and Snow',
		'Car': 'Chariot',
		'Dog': 'Doggo',
		'dog': 'doggo',
		'Person': 'Human',
		'person': 'human',
		'People': 'Humans',
		'people': 'humans',}
